server.port=8080
spring.application.name=deadline-analyzer
logging.level.root=WARN
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**
server.servlet.session.tracking-modes=cookie
spring.web.resources.cache.cachecontrol.max-age=0